export const serverBaseUrl: string = "https://localhost:44304/";
export const serverRegisterNewUserUrl = "https://localhost:44304/api/identity/register";
export const serverSignInUrl = "https://localhost:44304/api/identity/signIn";
export const serverUserProfileDetailsUrl = "https://localhost:44304/api/UserAccount/details";
export const serverUpdateUserProfileUrl = "https://localhost:44304/api/UserAccount/updateUserData";
export const serverUpdateUserPasswordUrl = "https://localhost:44304/api/UserAccount/changePassword";
export const serverResetUserPasswordUrl = "https://localhost:44304/api/UserAccount/resetPassword"
export const serverImageUploadUrl = "https://localhost:44304/api/upload/single"
export const serverExternalSignInUrl = "https://localhost:44304/api/identity/externalSignIn";
export const administrationGetAllUsers = "https://localhost:44304/api/administration";
export const serverGetAllAdvertisementsByUserIDUrl = "https://localhost:44304/api/advertisements/byUser";
export const administrationAddRoleToUserUrls = "https://localhost:44304/api/administration/addRole";
